export const phoneticsMap: { [word: string]: string; } = {
    "glacor": "glay-soar",
    "ardougne": "ar-doyn",
    "guthix": "goo-thicks",
    "saradomin": "sara-doh-min",
    "zamorak": "zamohrak",
    "bandos": "ban-doss",
    "armadyl": "arm-uh-dill",
    "sliske": "sliss-kay",
    "seren": "seh-ren",
    "kree'arra": "kree-uh-rah",
    "k'ril tsutsaroth": "krill tsoo-tsa-roth",
    "tirannwn": "tir-an-un",
    "geilinor": "Gill-in-or",
    "Morytania": "Mor-ee-tay-nee-ah",
    "Asgarnia": "As-gar-nee-ah",
    "Kandarin": "Can-dar-in",
    "Karamja": "Car-am-ja",
    "Ariane": "Aireeann",
    "Azzanadra": "Azzanahdra",
    "Camorra": "Cam-or-ah",
    "Charos": "Car-ross",
    "Drezel": "Drez-ell",
    "Duke Horacio": "Duke Hor-ah-see-oh",
    "forinthry": "for-in-three",
    "Zemouregal": "Zem-oh-ree-gal",
    "Zaros": "Zar-ross",
    "Zanik": "Zan-ick",
    "Zanaris": "Zan-ah-riss",
    "Zamorakian": "Zamohrackian",
    "Zamorakians": "Zamohrackians",
    "Zarosian": "Zarohseean",
    "Zarosians": "Zarohseeans",
    "Mahjarrat": "Mahjarat",
    "Icthlarin": "Ik-thlar-in",
    "ales" : "ails",
  };
  