export const phoneticsMap: { [word: string]: string; } = {
    "glacor": "glay-soar",
    "ardougne": "ar-doyn",
    "guthix": "goo-thicks",
    "saradomin": "sara-doh-min",
    "zamorak": "zam-oh-rack",
    "bandos": "ban-doss",
    "armadyl": "arm-uh-dill",
    "sliske": "sliss-kay",
    "seren": "seh-ren",
    "kree'arra": "kree-uh-rah",
    "k'ril tsutsaroth": "krill tsoo-tsa-roth",
    "tirannwn": "tir-an-un",
    "geilinor": "Gill-in-or",
    "Morytania": "Mor-ee-tay-nee-ah",
    "Asgarnia": "As-gar-nee-ah",
    "Kandarin": "Can-dar-in",
    "Karamja": "Car-am-ja",
    "Ariane": "Air-ee-ann",
    "Azzanadra": "Az-zan-ah-dra",
    "Camorra": "Cam-or-ah",
    "Charos": "Car-ross",
    "Drezel": "Drez-ell",
    "Duke Horacio": "Duke Hor-ah-see-oh",
  };
  