export const phoneticsMap: { [word: string]: string; } = {
  "glacor": "glaysoar",
  "ardougne": "ardoyn",
  "guthix": "guthicks",
  "saradomin": "saradohmin",
  "zamorak": "zamohrak",
  "bandos": "bandoss",
  "armadyl": "armuhdill",
  "sliske": "slisskay",
  "seren": "sehren",
  "kree'arra": "kreeuhrah",
  "k'ril tsutsaroth": "krill tsootsaroth",
  "tirannwn": "tiranun",
  "gielinor": "Gillinor",
  "morytania": "Moreetania",
  "kandarin": "Candarin",
  "karamja": "Caramja",
  "ariane": "Aireeann",
  "azzanadra": "Azzanahdra",
  "camorra": "Camorah",
  "charos": "Carross",
  "drezel": "Drezell",
  "duke horacio": "Duke Horahseeoh",
  "forinthry": "forinthree",
  "zemouregal": "Zemohreegal",
  "zaros": "Zarross",
  "zanik": "Zanick",
  "zanaris": "Zanahriss",
  "zamorakian": "Zamohrackian",
  "zamorakians": "Zamohrackians",
  "zarosian": "Zarohseean",
  "zarosians": "Zarohseeans",
  "mahjarrat": "Mahjarat",
  "icthlarin": "Ikthlarin",
  "ales" : "ails",
  "tier" : "tir",
  "adrasteia": "Adrahsteeya",
  "Iban": "eyeban",
};