export const phoneticsMap: { [word: string]: string; } = {
    "glacor": "glaysoar",
    "ardougne": "ardoyn",
    "guthix": "goothicks",
    "saradomin": "saradohmin",
    "zamorak": "zamohrak",
    "bandos": "bandoss",
    "armadyl": "armuhdill",
    "sliske": "slisskay",
    "seren": "sehren",
    "kree'arra": "kreeuhrah",
    "k'ril tsutsaroth": "krill tsootsaroth",
    "tirannwn": "tiranun",
    "gielinor": "Gillinor",
    "Morytania": "Moreetayneeah",
    "Asgarnia": "Asgarneeah",
    "Kandarin": "Candarin",
    "Karamja": "Caramja",
    "Ariane": "Aireeann",
    "Azzanadra": "Azzanahdra",
    "Camorra": "Camorah",
    "Charos": "Carross",
    "Drezel": "Drezell",
    "Duke Horacio": "Duke Horahseeoh",
    "forinthry": "forinthree",
    "Zemouregal": "Zemohreegal",
    "Zaros": "Zarross",
    "Zanik": "Zanick",
    "Zanaris": "Zanahriss",
    "Zamorakian": "Zamohrackian",
    "Zamorakians": "Zamohrackians",
    "Zarosian": "Zarohseean",
    "Zarosians": "Zarohseeans",
    "Mahjarrat": "Mahjarat",
    "Icthlarin": "Ikthlarin",
    "ales" : "ails",
    "Tier" : "tir"
  };
  